# Generated by Django 4.1.7 on 2024-09-02 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_userprofile_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='worker_type',
            field=models.CharField(blank=True, choices=[('electrician', 'Electrician'), ('plumber', 'Plumber'), ('painter', 'Painter'), ('carpenter', 'Carpenter'), ('cleaner', 'Cleaner'), ('interior-design-consultant', 'Interior Design Consultant')], max_length=50, null=True),
        ),
    ]
