# Generated by Django 4.1.7 on 2024-09-02 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_userprofile_worker_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
