# Generated by Django 4.1.7 on 2024-09-02 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='Worker',
        ),
    ]
