# Generated by Django 4.1.7 on 2024-09-02 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapp', '0008_remove_worker_user_delete_user_delete_worker'),
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=150)),
                ('role', models.CharField(max_length=150)),
                ('status', models.CharField(default='approved', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='workers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=150)),
                ('role', models.CharField(max_length=150)),
                ('work', models.CharField(max_length=150)),
                ('status', models.CharField(default='approved', max_length=150)),
            ],
        ),
    ]
