# Generated by Django 4.1.7 on 2024-09-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='workers',
        ),
        migrations.AddField(
            model_name='users',
            name='work',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
    ]
