# Generated by Django 4.1.7 on 2024-10-18 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_services_workers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='work',
            field=models.CharField(default='none', max_length=150),
        ),
    ]
