# Generated by Django 4.1.7 on 2024-10-18 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_users_work'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Services',
            new_name='Service_Details',
        ),
        migrations.RenameModel(
            old_name='Workers',
            new_name='Workers_Details',
        ),
    ]
