# Generated by Django 4.1.7 on 2024-10-20 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_rename_work_users_worker_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_details',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
