# Generated by Django 4.1.7 on 2024-10-23 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_bookings_worker_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookings',
            old_name='worker_id',
            new_name='worker',
        ),
    ]
