# Generated by Django 5.1 on 2024-10-27 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_workers_details_district_workers_details_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workers_details',
            name='district',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='workers_details',
            name='state',
            field=models.CharField(max_length=100),
        ),
    ]
