# Generated by Django 5.1 on 2025-01-28 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_alter_workers_details_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='bookings',
            name='working_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
