# Generated by Django 5.1 on 2025-01-29 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_bookings_status_bookings_working_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='timer_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookings',
            name='timer_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('timer_requested', 'Timer Requested'), ('in_progress', 'In Progress'), ('stop_requested', 'Stop Requested'), ('completed', 'Completed'), ('billed', 'Billed')], default='pending', max_length=20),
        ),
    ]
