# Generated by Django 5.1 on 2025-02-10 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_payment_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='work_completion_image',
            field=models.ImageField(blank=True, null=True, upload_to='work_completion_images/'),
        ),
        migrations.AddField(
            model_name='payment',
            name='work_completion_video',
            field=models.FileField(blank=True, null=True, upload_to='work_completion_videos/'),
        ),
    ]
