# Generated by Django 5.1 on 2025-03-11 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_servicelist'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.bookings')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.workers_details')),
            ],
            options={
                'get_latest_by': 'timestamp',
            },
        ),
    ]
